name: Terraform Destroy EC2
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: label-1
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Terraform Init
        run: terraform init
        working-directory: aws-doc   

      - name: Terraform Plan 
        run: terraform plan -destroy -out=tfplan
        working-directory: aws-doc

      - name: Terraform Destroy
        run: terraform destroy -auto-approve tfplan
        working-directory: aws-doc


