name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: label-1   # Or use 'ubuntu-latest' for GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        run: |
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
          sudo yum -y install terraform

      - name: Verify Terraform version
        run: terraform -v

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
  run: terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
