name: Terraform EC2 Destroy1

on:
  workflow_dispatch:   # manual trigger from Actions tab
  # You can also trigger on branch if you want:
  # push:
  #   branches:
  #     - cleanup

jobs:
  terraform-destroy:
    runs-on: label-1
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan
