name: Terraform EC2 Deploy

on:
  workflow_dispatch:   # allows manual trigger from Actions tab

jobs:
  terraform:
    runs-on: label-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: aws-doc 

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: aws-doc 

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: aws-doc 
